export const sizes = {
  S: {
    label: "Small (S)",
    length: "18–22 ft",
    sleeps: "2–3",
    ideal: "Weekend getaways, solo/duo trips",
    rig: "Travel Trailer",
    // img: `${IMG_BASE}/sizes-S-small-hero.webp`,
  },
  M: {
    label: "Medium (M)",
    length: "23–26 ft",
    sleeps: "3–4",
    ideal: "Small families, compact comfort",
    rig: "Travel Trailer",
    // img: `${IMG_BASE}/sizes-M-medium-hero.webp`,
  },
  L: {
    label: "Large (L)",
    length: "27–30 ft",
    sleeps: "4–6",
    ideal: "Families & friends, extra space",
    rig: "Travel Trailer",
    // img: `${IMG_BASE}/sizes-L-large-hero.webp`,
  },
  XL: {
    label: "Extra Large (XL)",
    length: "31–34 ft",
    sleeps: "6–8",
    ideal: "Bigger groups, comfort features",
    rig: "Travel Trailer / Fifth Wheel",
    // img: `${IMG_BASE}/sizes-XL-extralarge-hero.webp`,
  },
  XXL: {
    label: "Ultimate (XXL)",
    length: "35–40+ ft",
    sleeps: "8–10+",
    ideal: "Long stays, premium amenities",
    rig: "Fifth Wheel / Motorcoach (Class A)",
    // img: `${IMG_BASE}/sizes-XXL-ultimate-hero.webp`,
  },
};
