export const tiers = {
  Basic: {
    label: "Basic",
    diamonds: 1,
    note: "Reliable, essentials covered",
    color: "from-slate-600 to-slate-800",
    tag: "bg-slate-800 text-slate-200 border-slate-600",
    qualityScore: "75",
    images: [
      "./Large/large-(1).JPG",
      "./Large/large-(2).JPG",
      "./Large/large-(3).JPG",
      "./Large/large-(4).JPG",
    ],
    benefits: [
      "Clean & comfortable",
      "Well‑maintained systems",
      "Core essentials provided",
      "Reliable climate control",
    ],
  },
  Standard: {
    label: "Standard",
    diamonds: 2,
    note: "Newer models & more features",
    color: "from-cyan-500 to-cyan-700",
    tag: "bg-cyan-900 text-cyan-200 border-cyan-600",
    qualityScore: "85",
    images: [
      "./Medium/medium(3).png",
      "./Medium/medium(2).jpg",
      "./Medium/medium(1).jpg",
      "./Medium/medium(4).webp",
    ],
    benefits: [
      "Newer model or finish",
      "Convenience‑focused amenities",
      "Additional comfort touches",
      "Refined interior details",
    ],
  },
  Premium: {
    label: "Premium",
    diamonds: 3,
    note: "Top-tier, feature-rich & like-new",
    color: "from-cyan-400 via-fuchsia-400 to-purple-600",
    tag: "bg-gradient-to-r from-cyan-950 via-fuchsia-950 to-purple-950 text-fuchsia-200 border-fuchsia-700",
    qualityScore: "95",
    images: [
      "./XXL/XXL(1).JPG",
      "./XXL/XXL(2).JPG",
      "./XXL/XXL(3).JPG",
      "./XXL/XXL(4).JPG",
    ],
    benefits: [
      "High comfort standard",
      "Modern interiors &amp; finishes",
      "Feature‑forward package",
      "Exceptional overall condition",
    ],
  },
};
