import "@/globals.css";
import { ReduxProvider } from "./_lib/store/ReduxProvider";
import QueryProvider from "@/_lib/QueryProvider";

export const metadata = {
  title: "RV",
  description: "Generated by Next.js",
};

export default function Root({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#0a1024]">
        <QueryProvider>
          <ReduxProvider>{children}</ReduxProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
