import "@/globals.css";
import Header from "@/_ui/Header";

export const metadata = {
  title: "SurprisePlanner",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#020618]">
        <Header />
        {children}
      </body>
    </html>
  );
}
